<?php

use GlobalPayments\PaymentGateway\Block\Adminhtml\Order\View\DigitalWalletsAddress;

/**
 * @var DigitalWalletsAddress $block
 */

$allowedAddressHtmlTags = ['br'];
?>
<?php if ($block->canDisplayInfo()): ?>
    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml($block->getTitle()) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <?php /* Billing Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </div>
                <address class="admin__page-section-item-content">
                    <?= $block->escapeHtml($block->getBillingAddress(), $allowedAddressHtmlTags); ?>
                </address>
            </div>
            <?php if ($block->getShippingAddress()): ?>
                <div class="admin__page-section-item order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    </div>
                    <address class="admin__page-section-item-content">
                        <?= $block->escapeHtml($block->getShippingAddress(), $allowedAddressHtmlTags); ?>
                    </address>
                </div>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>
