<?php
use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;
use GlobalPayments\Api\Entities\Enums\ManualEntryMethod;
use GlobalPayments\PaymentGateway\Gateway\Config;

/** @var Magento\Vault\Block\Form $block */
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$publicHash = $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH);
$id = $escaper->escapeHtml($block->getData('id'));
$code = $escaper->escapeHtml($block->getData('code'));

$entryMode = '';

if ($code === Config::CODE_GPAPI_VAULT) {
    $entryMode = ManualEntryMethod::MOTO;
}
?>
<fieldset data-mage-init='{
        "GlobalPayments_PaymentGateway/js/vault": {
            "code": "<?= $escaper->escapeHtml($code); ?>",
            "container": "payment_<?= /* @noEscape */ $id; ?>",
            "publicHash": "<?= $escaper->escapeHtml($publicHash); ?>"
        }
    }' id="payment_<?= /* @noEscape */ $id; ?>" class="admin__fieldset">
    <?php if (isset($details)): ?>
        <div class="admin__field-control control">
            <input
                type="radio"
                id="token_switcher_<?= /* @noEscape */ $id; ?>"
                name="payment[token_switcher]"
                style="margin-left:24px" />
            <span><?= $escaper->escapeHtml(__('ending'));?></span>
            <span><?= $escaper->escapeHtml($details['maskedCC']); ?></span>
            (<span><?= $escaper->escapeHtml(__('expires'));?></span>:
            <span><?= $escaper->escapeHtml($details['expirationDate']); ?></span>)
        </div>
    <?php endif; ?>
    <input
        type="hidden"
        name="payment[entryMode]"
        value="<?= $escaper->escapeHtml($entryMode); ?>" />
</fieldset>
